name: contact
channels:
  - anaconda
  - davidcaron
  - nvidia/label/cuda-11.3.1
  - nvidia/label/cuda-11.8.0
  - nvidia/label/cuda-11.3.0
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - async-timeout=4.0.3
  - blas=1.0
  - blinker=1.6.2
  - boost-cpp=1.70.0
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.2.2
  - cachetools=4.2.2
  - certifi=2024.2.2
  - cffi=1.14.0
  - chardet=4.0.0
  - click=8.1.7
  - cmake=3.22.1
  - cryptography=2.9.2
  - cuda=11.3.0
  - cuda-cccl=11.8.89
  - cuda-command-line-tools=11.8.0
  - cuda-compiler=11.8.0
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cuobjdump=11.8.86
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=11.8.86
  - cuda-documentation=11.8.86
  - cuda-driver-dev=11.8.89
  - cuda-gdb=11.8.86
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.8.89
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.8.86
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.8.86
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-nvvp=11.8.87
  - cuda-profiler-api=11.8.86
  - cuda-runtime=11.3.0
  - cuda-samples=11.3.58
  - cuda-sanitizer-api=11.8.86
  - cuda-thrust=11.3.58
  - cuda-toolkit=11.8.0
  - cuda-tools=11.8.0
  - cuda-version=11.8
  - cuda-visual-tools=11.8.0
  - cudatoolkit=11.8.0
  - cudatoolkit-dev=11.4.0
  - cudnn=8.9.7.29
  - cycler=0.11.0
  - dbus=1.13.18
  - eigen=3.4.0
  - expat=2.6.2
  - flann=1.9.1
  - fontconfig=2.14.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gds-tools=1.4.0.31
  - glib=2.65.0
  - google-auth-oauthlib=0.5.2
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.7
  - intel-openmp=2021.4.0
  - joblib=1.4.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - laspy=2.0.3
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcurl=8.2.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.8
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=13.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libnghttp2=1.52.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.4.0
  - libuuid=1.41.5
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.4.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - multidict=6.0.4
  - nccl=2.21.5.1
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nsight-compute=2022.3.0.22
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1w
  - pandas=1.2.4
  - pcl=1.9.1
  - pclpy=0.12.0
  - pcre=8.45
  - pip=23.3.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyopenssl=19.1.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2024.1
  - qhull=2020.2
  - qt=5.9.7
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rhash=1.4.1
  - rsa=4.7.2
  - seaborn=0.12.2
  - setuptools=68.2.2
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.45.3
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - urllib3=2.1.0
  - werkzeug=2.3.8
  - wheel=0.43.0
  - xz=5.2.5
  - yarl=1.9.3
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - addict==2.4.0
    - aiofiles==22.1.0
    - aiosqlite==0.20.0
    - albumentations==1.3.1
    - antlr4-python3-runtime==4.9.3
    - anyio==4.0.0
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - asciitree==0.3.3
    - asttokens==2.4.1
    - attrs==23.2.0
    - babel==2.14.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - blitz-bayesian-pytorch==0.2.8
    - charset-normalizer==3.3.2
    - chumpy==0.67.5
    - cirq==1.1.0
    - cirq-aqt==1.1.0
    - cirq-core==1.1.0
    - cirq-google==1.1.0
    - cirq-ionq==1.1.0
    - cirq-pasqal==1.1.0
    - cirq-rigetti==1.1.0
    - cirq-web==1.1.0
    - cloudpickle==1.5.0
    - comm==0.2.2
    - cython==0.29.21
    - debugpy==1.8.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecated==1.2.14
    - deprecation==2.1.0
    - distro==1.9.0
    - duet==0.2.8
    - easydict==1.13
    - einops==0.8.0
    - etils==1.3.0
    - exceptiongroup==1.1.3
    - executing==2.0.1
    - fasteners==0.15
    - fastjsonschema==2.19.1
    - ffnet==0.8.4
    - filelock==3.13.1
    - freetype-py==2.4.0
    - fsspec==2024.3.1
    - future==0.18.2
    - fvcore==0.1.5.post20221221
    - git-filter-repo==2.45.0
    - glfw==2.9.0
    - google-api-core==1.34.0
    - google-auth==1.35.0
    - googleapis-common-protos==1.60.0
    - grpcio==1.57.0
    - grpcio-status==1.57.0
    - h11==0.14.0
    - h5py==3.6.0
    - httpcore==0.16.3
    - httpx==0.23.3
    - hydra-core==0.11.3
    - imageio==2.34.0
    - imagesize==1.2.0
    - importlib-metadata==5.0.0
    - importlib-resources==6.4.0
    - imutils==0.5.4
    - iopath==0.1.9
    - ipykernel==6.29.3
    - ipython==8.12.3
    - ipython-genutils==0.2.0
    - ipywidgets==8.1.2
    - iso8601==1.1.0
    - jedi==0.19.1
    - jinja2==3.1.3
    - json5==0.9.24
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.1
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-packaging==0.12.3
    - jupyter-server==2.13.0
    - jupyter-server-fileid==0.9.1
    - jupyter-server-terminals==0.5.3
    - jupyter-server-ydoc==0.8.0
    - jupyter-ydoc==0.2.5
    - jupyterlab==3.6.7
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.4
    - jupyterlab-widgets==3.0.10
    - kornia==0.6.11
    - lark==0.11.3
    - lazy-loader==0.3
    - lightglue==0.0
    - lit==17.0.6
    - llvmlite==0.41.1
    - lr-scheduler==0.1
    - mako==1.3.3
    - manopth==0.0.1
    - markupsafe==2.1.5
    - matplotlib-inline==0.1.6
    - mistune==3.0.2
    - mock==4.0.2
    - monotonic==1.5
    - mpmath==1.3.0
    - msgpack==1.0.5
    - mujoco==3.2.3
    - mujoco-python-viewer==0.1.4
    - nbclassic==1.0.0
    - nbclient==0.10.0
    - nbconvert==7.16.3
    - nbformat==5.10.3
    - nest-asyncio==1.6.0
    - networkx==2.8
    - notebook==6.5.6
    - notebook-shim==0.2.4
    - numba==0.58.1
    - numcodecs==0.6.4
    - numpy==1.23.5
    - nvidia-cublas==11.5.1.101
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc==11.1.105
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime==11.3.58
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-nccl-cu11==2.20.5
    - nvidia-nvtx-cu11==11.8.86
    - nvidia-pyindex==1.0.9
    - nvidia-tensorrt==7.2.3.4
    - omegaconf==2.3.0
    - open3d==0.13.0
    - opencv-python==4.12.0.88
    - opencv-python-headless==4.11.0.86
    - overrides==7.7.0
    - packaging==24.0
    - pandocfilters==1.5.1
    - parso==0.8.3
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pillow==9.0.1
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.2.1
    - portalocker==1.7.0
    - poselib==2.0.0
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.43
    - proto-plus==1.22.3
    - protobuf==3.20.3
    - psutil==5.9.8
    - ptflops==0.7
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyclean==2.7.6
    - pycocotools==2.0.1
    - pycolmap==0.6.1
    - pycuda==2024.1
    - pydantic==1.10.12
    - pydot==1.4.1
    - pyglet==2.0.16
    - pygments==2.17.2
    - pyjwt==2.8.0
    - pyopengl==3.1.0
    - pyopengl-accelerate==3.1.7
    - pyquil==3.5.4
    - pyrealsense2==2.49.0.3474
    - pyrender==0.1.45
    - python-json-logger==2.0.7
    - python-rapidjson==1.10
    - pytlsd==0.0.2
    - pytools==2024.1.2
    - pytorch-crf==0.7.2
    - pytorch-triton-rocm==2.3.1
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - qcs-api-client==0.21.6
    - qudida==0.0.4
    - referencing==0.34.0
    - retrying==1.3.4
    - rfc3339==6.2
    - rfc3339-validator==0.1.4
    - rfc3986==1.5.0
    - rfc3986-validator==0.1.1
    - rpcq==3.11.0
    - rpds-py==0.18.0
    - ruamel-yaml==0.17.32
    - ruamel-yaml-clib==0.2.7
    - scikit-build==0.17.6
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - send2trash==1.8.2
    - smplx==0.1.28
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soupsieve==2.5
    - spacepy==0.2.3
    - stack-data==0.6.3
    - sympy==1.12
    - tabulate==0.8.7
    - tenacity==8.2.3
    - tensorboardx==2.4
    - tensorrt==7.2.3.4
    - termcolor==1.1.0
    - terminado==0.18.1
    - thop==0.1.1-2209072238
    - tifffile==2023.7.10
    - timm==0.4.5
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomlkit==0.12.4
    - torch==2.3.1+cu118
    - torch-bnn==0.3.8
    - torchaudio==2.3.1+cu118
    - torchbnn==1.2
    - torchgeometry==0.1.2
    - torchlight==0.0.1
    - torchmetrics==0.11.1
    - torchsummary==1.5.1
    - torchvision==0.18.1+cu118
    - tornado==6.4
    - tqdm==4.47.0
    - traitlets==5.14.2
    - trimesh==4.4.3
    - triton==2.3.1
    - types-deprecated==1.2.9.3
    - types-python-dateutil==2.8.19.14
    - types-retry==0.9.9.4
    - typing-extensions==4.11.0
    - warmup-scheduler==0.3
    - wcwidth==0.2.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - widgetsnbextension==4.0.10
    - wrapt==1.15.0
    - y-py==0.6.2
    - yacs==0.1.7
    - ypy-websocket==0.8.4
    - zarr==2.4.0
    - zipp==3.9.0
prefix: /home/hao/anaconda3/envs/contact
