model_save_name: 1
model_save_dir: ./runs/ikea/bpgcn_SN_max3_res_no_sn/
work_dir: ./work_dir/ikea/bpgcn_SN_max3_res_no_sn/
optimizer: SGD

# model
model: model.bpgcn_SN_max3_res_no_sn.Model
model_args:
  num_class: 32
  num_person: 1
  num_point: 20
  coeff: 3.0
  graph: graph.bimacs_partbdy.Graph
  graph_b: graph.ikea.Graph
  dataset: 'ikea' # 'bimacs'
  graph_args:
    labeling_mode: 'spatial'
  in_channels: 2

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 500
  data_path: /media/dataset/IKEA/processed/data2/xenv_train_2d_data_joint_20.npy
  label_path: /media/dataset/IKEA/processed/data2/xenv_train_label.pkl
  debug: False

test_feeder_args:
  data_path: /media/dataset/IKEA/processed/data2/xenv_test_2d_data_joint_20.npy
  label_path: /media/dataset/IKEA/processed/data2/xenv_test_label.pkl
  debug: False

# optim
weight_decay: 0.0001
base_lr: 0.1
step: [20, 40]

# training
device: [0]
batch_size: 2
test_batch_size: 8
num_epoch: 60
nesterov: True
