work_dir: ./work_dir/ikea/spa_psp
model_saved_name: ./runs/ikea/stgcn_d500_g100/spa_psp

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 500
  data_path: /data/IKEA/processed_d500_g100/xenv_train_2d_data_joint_20.npy
  label_path: /data/IKEA/processed_d500_g100/xenv_train_label.pkl
  debug: False

test_feeder_args:
  data_path: /data/IKEA/processed_d500_g100/xenv_test_2d_data_joint_20.npy
  label_path: /data/IKEA/processed_d500_g100/xenv_test_label.pkl
  debug: False

# model
# model: model.spa_jpu_psp_best.Model
model: model.spa_jpu_psp_conv.Model
model_args:
  num_class: 32
  num_person: 1
  num_point: 20
  graph: graph.ikea.Graph
  graph_args:
    labeling_mode: 'spatial'
  in_channels: 2

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [20, 40]

# training
device: [0]
batch_size: 8
test_batch_size: 8
num_epoch: 60
nesterov: True




